### PR TITLE
AEDSPUtilities: added AEDSPClearBufferList & AEDSPClearAudioBuffer

### PR DESCRIPTION
**Pull request by 32Beat**
I would like to see these or something similar added to the AEDSPUtilities, thx

### CODE REVIEW

**Comment by michaeltyson** [comment]
Hmm, I dunno about the duplication of functionality that's in AEAudioBufferListUtilities. Feels a bit messy...

**Comment by 32Beat** [comment]
Well, if you have the functionality, why aren't you using it? 

But this specific choice is meant to indicate that we're clearing float buffers since vDSP is specifically targeting floating point vectors, and hence we don't need the streamformat. 

I'm okay stuffing it elsewhere, as long as we also make a choice about what to do with the mDataByteSize field. I eventually decided that the OS uses it as an output indicator: "I manipulated this many bytes", or "this many bytes are now valid". It (clearly) has no relation with the size of the pointer behind data. 

Also, do we have a namingconvention perhaps like:
AEDSPBufferListClearFrames and AEDSPAudioBufferClearFrames

**Comment by michaeltyson** [comment]
Anywhere in particular you see it not being used where it should be? I'm using it in most places...

**Comment by 32Beat** [comment]
https://github.com/TheAmazingAudioEngine/TAAE2/commit/c83e19e09fa22e6dccc2828a472de9e2296759e7

There are other places where this loop occurs one way or another. In my experience, generally when you write the same functionality  (particularly some kind of loop) more than once, immediately consider a helper function so that you can implement uniform behavior and write it only once. Write it once => means less effort now and particularly in the future, since making mistakes occurs in one place only. (I presume the advantages in debugging & maintenance are obvious.)

NB: I still think the above commit did not solve the real issue of whether or not to set the mDataByteSize field when clearing the buffer.

**Comment by michaeltyson** [comment]
I've done a scan through, yep, there are a few places where I didn't use it. Fixed.

**Pull request closed without merging**
